[workspace]
members = [
  "lux-lib",
  "lux-cli",
  "lux-lua",
  "lux-workspace-hack",
  "xtask",
  "xtask-lua",
]
default-members = ["lux-cli", "lux-lib"]
resolver = "2"

[workspace.package]
version = "0.7.4"

[profile.release]
lto = true
codegen-units = 1
