[package]
name = "rocks"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.17", features = ["derive"] }
eyre = "0.6.11"
git-url-parse = "0.4.4"
git2 = "0.18.2"
itertools = "0.12.0"
nucleo = "0.3.0"
octocrab = "0.34.0"
rocks-lib = { path = "../rocks-lib/" }
rustyline = "13.0.0"
termcolor = "1.4.1"
text_trees = "0.1.2"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
