---
name: "Nix build"
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build:
    name: ${{ matrix.attribute }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        attribute:
          - .#devShells.x86_64-linux.default
          - .#packages.x86_64-linux.rocks
          - .#checks.x86_64-linux.git-hooks-check
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v9
    - uses: cachix/cachix-action@v14
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # Some of the tests query luarocks.org. TODO: Get sandboxed tests working
    - run: nix build "${{matrix.attribute}}"
