---
name: "Nix build"
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    permissions:
      id-token: "write"
      contents: "read"
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-20.04, target: x86_64-linux }
          - { os: macos-13, target: x86_64-darwin }
          - { os: macos-14, target: aarch64-darwin }
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: cachix/cachix-action@v16
      with:
        name: neorocks
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Formatting
      run: nix build ".#checks.${{matrix.job.target}}.git-hooks-check" --accept-flake-config --log-lines 500
      if: ${{ matrix.job.target == 'x86_64-linux' }}
      shell: bash
    - name: Clippy
      run: nix build ".#checks.${{matrix.job.target}}.clippy" --accept-flake-config --log-lines 500
      shell: bash
    - name: Tests
      run: nix build ".#checks.${{matrix.job.target}}.tests" --accept-flake-config --log-lines 500
      shell: bash
    - name: Build devShell
      run: nix build ".#devShells.${{matrix.job.target}}.default" --accept-flake-config --log-lines 500
      shell: bash
    - name: Build package
      run: nix build ".#packages.${{matrix.job.target}}.default" -Lv --accept-flake-config
      shell: bash
