---
name: update-luau
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Update Luau
        run: nix run .#update-luau
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          branch: update-luau
          title: "chore: update luau"
          commit-message: "chore: update luau"
          delete-branch: true
